version: '2'
services:
  funpark-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/funpark/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=funpark
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
